name: TechnionPytorch
channels:
  - pytorch
  - defaults
dependencies:
  - alabaster=0.7.12=py36_0
  - astroid=2.5=py36haa95532_1
  - attrs=19.3.0=py_0
  - autovizwidget=0.13.1=py_0
  - babel=2.9.0=pyhd3eb1b0_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - brotlipy=0.7.0=py36h2bbff1b_1003
  - ca-certificates=2021.1.19=haa95532_1
  - certifi=2020.12.5=py36haa95532_0
  - cffi=1.14.5=py36hcd4344a_0
  - chardet=4.0.0=py36haa95532_1003
  - cloudpickle=1.3.0=py_0
  - colorama=0.4.3=py_0
  - console_shortcut=0.1.1=4
  - cryptography=3.4.7=py36h71e12ea_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cycler=0.10.0=py36h009560c_0
  - cytoolz=0.10.1=py36he774522_0
  - dask-core=2.13.0=py_0
  - dataclasses=0.8=pyh4f3eec9_6
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.17=py36haa95532_1
  - entrypoints=0.3=py36_0
  - freetype=2.9.1=ha9979f8_1
  - hdf5=1.8.20=hac2f561_1
  - hdijupyterutils=0.12.9=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.10=pyhd3eb1b0_0
  - imageio=2.8.0=py_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - isort=5.8.0=pyhd3eb1b0_0
  - jedi=0.16.0=py36_1
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py36_0
  - jupyter_client=6.1.0=py_0
  - jupyter_core=4.6.1=py36_0
  - keyring=22.3.0=py36haa95532_0
  - kiwisolver=1.1.0=py36ha925a31_0
  - lazy-object-proxy=1.6.0=py36h2bbff1b_0
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.1.0=h56a325e_0
  - libuv=1.40.0=he774522_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36he774522_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36h64f37c6_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36he774522_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36hb782905_0
  - mkl_fft=1.0.15=py36h14836fe_0
  - mkl_random=1.1.0=py36h675688f_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - networkx=2.4=py_0
  - ninja=1.10.2=py36h6d14046_0
  - notebook=6.0.3=py36_0
  - numpy=1.18.1=py36h93ca92e_0
  - numpy-base=1.18.1=py36hc3f5095_1
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h40b0b35_0
  - openssl=1.1.1k=h2bbff1b_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.0.3=py36h47e9c7a_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.6.2=py_0
  - patsy=0.5.1=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hcc1f983_0
  - pip=20.0.2=py36_1
  - plotly=4.5.2=py_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - psutil=5.8.0=py36h2bbff1b_1
  - py-opencv=3.4.2=py36hc319ecb_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.6.1=py_0
  - pylint=2.7.4=py36haa95532_1
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h6538335_2
  - pyrsistent=0.15.7=py36he774522_0
  - pysocks=1.7.1=py36haa95532_0
  - python=3.6.10=h9f7ef89_1
  - python-dateutil=2.8.1=py_0
  - pytorch=1.7.1=py3.6_cuda101_cudnn7_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36he774522_0
  - pywin32=227=py36he774522_1
  - pywin32-ctypes=0.2.0=py36_1000
  - pywinpty=0.5.7=py36_0
  - pyzmq=18.1.1=py36ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.2=pyhd3eb1b0_0
  - qtconsole=5.0.3=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - requests=2.25.1=pyhd3eb1b0_0
  - retrying=1.3.3=py36_2
  - rope=0.18.0=py_0
  - scikit-image=0.16.2=py36h47e9c7a_0
  - scikit-learn=0.22.1=py36h6288b17_0
  - scipy=1.4.1=py36h9439919_0
  - send2trash=1.5.0=py36_0
  - setuptools=46.1.1=py36_0
  - sip=4.19.8=py36h6538335_0
  - six=1.14.0=py36_0
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sphinx=3.5.3=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
  - spyder=3.3.6=py36_0
  - spyder-kernels=0.5.2=py36_0
  - sqlite=3.31.1=he774522_0
  - statsmodels=0.11.0=py36he774522_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hfa6e2cd_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.10.0=py_0
  - torchaudio=0.7.2=py36
  - torchvision=0.8.2=py36_cu101
  - tornado=6.0.4=py36he774522_1
  - tqdm=4.43.0=py_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.2=py36h2bbff1b_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - win_inet_pton=1.1.0=py36haa95532_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py36he774522_1
  - xz=5.2.4=h2fa13f4_4
  - zeromq=4.3.1=h33f27b4_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - barbar==0.2.1
    - sklearn==0.0
prefix: D:\Programing\Anaconda3\envs\TechnionPytorch

